apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: position-service
  name: position-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: position-service
    spec:
      containers:
        - name: position-service
          env:
            - name: DATABASE_TCP_HOST
              value: database
          image: traderx/position-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 18090
              protocol: TCP
          workingDir: /position-service
      restartPolicy: Always

