name: Build and Publish Application Images

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  VERSION: 'latest'
  CONTAINER_REGISTRY: 'ghcr.io/finos'
 
jobs:
  build-ghcr:
    name: Build and push application images to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - directory: traderX/account-service/
            image: traderX/account-service
          - directory: traderX/database/
            image: traderX/database
          - directory: traderX/ingress/
            image: traderX/ingress
          - directory: traderX/people-service/
            image: traderX/people-service
          - directory: traderX/position-service/
            image: traderX/position-service
          - directory: traderX/reference-data/
            image: traderX/reference-data
          - directory: traderX/trade-feed/
            image: traderX/trade-feed
          - directory: traderX/trade-processor/
            image: traderX/trade-processor
          - directory: traderX/trade-service/
            image: traderX/trade-service
          - directory: traderX/web-front-end/angular/
            image: traderX/web-front-end-angular
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ${{ matrix.image }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.directory }}
          push: ${{ github.event_name == 'push' && true || false }}
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ matrix.image }}:${{ env.VERSION }}